### ISSUE TITLE
Error HTTP422 when running the FhirBridgeApplicationIT in Mapping BodyHeight

### ISSUE THREAD

**Issue by BirgitSaalfeld** [ehrbase/fhir-bridge#16]
I did my mapping with the BodyHeight in a branch. 5ebabea37199e0b6f64130223ffafe0e3e419e17

When I try to run the test "createObservationBodyHeight" I receive following message: 

```
ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 : Profile http://hl7.org/fhir/StructureDefinition/vitalsigns is not supported for Observation. One of the following profiles is expected: [http://hl7.org/fhir/StructureDefinition/bodytemp, http://hl7.org/fhir/StructureDefinition/bodyheight, https://charite.infectioncontrol.de/fhir/core/StructureDefinition/CoronavirusNachweisTest, https://www.medizininformatik-initiative.de/fhir/core/StructureDefinition/ObservationLab]

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:302)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:351)
	at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:540)
	at ca.uhn.fhir.rest.client.impl.GenericClient$CreateInternal.execute(GenericClient.java:687)
	at ca.uhn.fhir.rest.client.impl.GenericClient$CreateInternal.execute(GenericClient.java:642)
	at org.ehrbase.fhirbridge.FhirBridgeApplicationIT.createObservationBodyHeight(FhirBridgeApplicationIT.java:431)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:74)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

**Comment by ppazos** [comment]
@BirgitSaalfeld 

- the link to the branch is https://github.com/ehrbase/fhir-bridge/compare/feature/num10_mapping-body-height

- the profile doesn't seem to be loaded: Profile http://hl7.org/fhir/StructureDefinition/vitalsigns is not supported for Observation

- the error is captured by the client here https://github.com/ehrbase/fhir-bridge/compare/feature/num10_mapping-body-height#diff-11fd6d80577350c58b9616fb5f15b644R431

- I think this is the check that fails and were the exception is thrown: https://github.com/ehrbase/fhir-bridge/compare/feature/num10_mapping-body-height#diff-d0302321c8ee953e17f92b206fd17c6dR476-R490

- please check ProfileUtils because this should return true for the new profile and maybe it wasn't loaded: ProfileUtils.hasProfile(observation, Profile.BODY_HEIGHT)

**Comment by birgerhaarbrandt** [comment]
This might be as well related to using the dif of the profile and not the snapshot that would also contain information about the basis resource. Please go to the simplifier project and download the profile XMK again as snapshot

**Comment by BirgitSaalfeld** [comment]
> This might be as well related to using the dif of the profile and not the snapshot that would also contain information about the basis resource. Please go to the simplifier project and download the profile XML again as snapshot

@birgerhaarbrandt At the moment I use the xml-document I get from this site: https://simplifier.net/ForschungsnetzCovid-19/BodyHeight/~xml This seems to be only the diff. Where can I find the full definition/declaration/xml-file?

**Comment by BirgitSaalfeld** [comment]
> @BirgitSaalfeld
> 
> * the link to the branch is https://github.com/ehrbase/fhir-bridge/compare/feature/num10_mapping-body-height
> * the profile doesn't seem to be loaded: Profile http://hl7.org/fhir/StructureDefinition/vitalsigns is not supported for Observation
> * the error is captured by the client here https://github.com/ehrbase/fhir-bridge/compare/feature/num10_mapping-body-height#diff-11fd6d80577350c58b9616fb5f15b644R431
> * I think this is the check that fails and were the exception is thrown: https://github.com/ehrbase/fhir-bridge/compare/feature/num10_mapping-body-height#diff-d0302321c8ee953e17f92b206fd17c6dR476-R490
> * please check ProfileUtils because this should return true for the new profile and maybe it wasn't loaded: ProfileUtils.hasProfile(observation, Profile.BODY_HEIGHT)

Thanks for the hints. How can I check ProfileUtils? I think you didn't meant adding it in the Use-Case-Test!?

**Comment by ppazos** [comment]
@BirgitSaalfeld I meant to debug what happens in the code of https://github.com/ehrbase/fhir-bridge/blob/develop/src/main/java/org/ehrbase/fhirbridge/fhir/ProfileUtils.java#L30

You can try to run it in debug mode from the IDE and add a couple of breakpoints to see what are the loaded profiles. I'll try to test it on my environment.

**Comment by ppazos** [comment]
@BirgitSaalfeld in the code, the profiles should be loaded from the resources/profiles folder by this piece of code:

https://github.com/ehrbase/fhir-bridge/blob/develop/src/main/java/org/ehrbase/fhirbridge/config/FhirConfiguration.java#L142-L152

Can you check when you run the code if this exception appears somewhere:

` throw new FhirBridgeException("Profiles initialization failed", e);`

That will signal the profile wasn't loaded.

**Comment by ppazos** [comment]
@BirgitSaalfeld also I found this error: in the resource you are using for bodyheight-example.json the profile is:

```
"profile": [
      "http://hl7.org/fhir/StructureDefinition/vitalsigns"
    ]
```

It should be the body height profile.

**Comment by BirgitSaalfeld** [comment]
> @BirgitSaalfeld also I found this error: in the resource you are using for bodyheight-example.json the profile is vital signs:
> 
> ```
> "profile": [
>       "http://hl7.org/fhir/StructureDefinition/vitalsigns"
>     ]
> ```
> 
> It should be the body height profile.

@ppazos  In fact, that sounds weird. I got my json-example from here: http://hl7.org/fhir/R4/observation-example-body-height.xml.html And there is the vitalsigns-entry in the profile. I think it is an error in the resource. That's why I manually changed the entry to 'bodyheight'.
```
    "profile": [
      "http://hl7.org/fhir/StructureDefinition/bodyheight"
    ]
```

This error is fixed. Thank you. =D But now I get another error: 
```
ca.uhn.fhir.rest.server.exceptions.ResourceNotFoundException: HTTP 404 : EHR for patient example doesn't exists
```

**Comment by ppazos** [comment]
@BirgitSaalfeld don't trust the sources :)

the error message is signaling in ehrbase there is no EHR for the patient in the FHIR resource. Get using the rest API of ehrbase to create one pointing to the subjectId in the resource.

I uploaded a video, shared on the plri slack about how to do that.

**Comment by ppazos** [comment]
@BirgitSaalfeld I think the original issue was solved, can we close the issue?

**Comment by BirgitSaalfeld** [comment]
> @BirgitSaalfeld I think the original issue was solved, can we close the issue?

Yes, but what is your preferred way? I saw, you moved it to "Ready for Review". Can I be your reviewer? Am I allowed to move it directly to "done"? Does it move to "done" automatically when I close it?

**Comment by BirgitSaalfeld** [comment]
> I uploaded a video, shared on the plri slack about how to do that.

I am still working through your videos. Thank you for this support. There is so much information in the videos and, as you know for sure, I am a newby in FHIR and openEHR and have much to lean ;) Hopefully I get soon to the corresponding video passage.

**Comment by ppazos** [comment]
@BirgitSaalfeld if you give me the ok, I can close it :)

**Comment by BirgitSaalfeld** [comment]
> @BirgitSaalfeld if you give me the ok, I can close it :)

@ppazos You can close it, but I want to understand the process better, since I am going to work in this process at least until end of march. Who can answer my questions from the last post, since they are a mix of github and project specific concerns.

**Comment by ppazos** [comment]
@BirgitSaalfeld in terms of reviewing tickets to close, that is more related to when the assignee needs to do a task. This ticket was really to assist you with a problem, even though I tested and debugged your branch to find the issues, I do not have an outcome to be reviewed. So the acceptance criteria was really that the initial issue reported by you was solved with the support I gave.

In case of your ticket, that is actually to get some outcome, when you have it working, you need to send a PR from your branch (I suggest to pull and merge develop before that to solve any conflicts first). Then for the PR you can ask for a reviewer (I can be the reviewer). I like to do a static code review first, then we could have a call where you show how your changes work, if everything looks OK it is approved and merged with develop. The reviewer might ask for changes and then can do a final review an merge then.

Hope that helps.

This might also help: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
