### ISSUE TITLE
Unexpected server error on posting sofa-score Observation

### ISSUE THREAD

**Issue by wlad** [ehrbase/fhir-bridge#300]
## Test Case/s To Reproduce Issue With Robot

```
# path to test case
tests/robot/OBSERVATION/01_create.robot
TC:  103 Create Sofa Score value instant
```

```
# robot command to execute related test case(s) in your terminal/console

robot -i 300 -d results -L TRACE robot

```

## Steps To Reproduce Manually

```json
{
    "request": {
        "method": "POST",
        "url": "http://localhost:8888/fhir-bridge/fhir/Observation",
        "scheme": "http",
        "netloc": "localhost:8888",
        "path": "/fhir-bridge/fhir/Observation",
        "query": {},
        "body": {
            "resourceType": "Observation",
            "id": "sofa-score",
            "status": "final",
            "meta": {
                "profile": [
                    "https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/sofa-score"
                ]
            },
            "category": [
                {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                            "code": "survey",
                            "display": "Survey"
                        }
                    ]
                }
            ],
            "code": {
                "coding": [
                    {
                        "system": "https://www.netzwerk-universitaetsmedizin.de/fhir/CodeSystem/ecrf-parameter-codes",
                        "code": "06",
                        "display": "SOFA-Score"
                    }
                ],
                "text": "Sepsis-related organ failure assessment score"
            },
            "subject": {
                "identifier": {
                    "system": "urn:ietf:rfc:4122",
                    "value": "1c11abd8-5219-4c05-97a9-4ed0647f521b"
                }
            },
            "effectiveInstant": "2020-09-07T13:28:17.239+02:00",
            "component": [
                {
                    "code": {
                        "coding": [
                            {
                                "system": "https://www.netzwerk-universitaetsmedizin.de/fhir/CodeSystem/sofa-score",
                                "code": "resp",
                                "display": "Respiratory system"
                            }
                        ],
                        "text": "SOFA Respiratory system scoring category"
                    },
                    "valueCodeableConcept": {
                        "coding": [
                            {
                                "system": "https://www.netzwerk-universitaetsmedizin.de/fhir/CodeSystem/sofa-score",
                                "code": "resp3",
                                "display": "Respiratory system SOFA score 3"
                            }
                        ],
                        "text": "PaO2/FiO2 [mmHg (kPa)] < 200 (26.7) and mechanically ventilated"
                    }
                },
                {
                    "code": {
                        "coding": [
                            {
                                "system": "https://www.netzwerk-universitaetsmedizin.de/fhir/CodeSystem/sofa-score",
                                "code": "ns",
                                "display": "Nervous system"
                            }
                        ],
                        "text": "SOFA Nervous system scoring category"
                    },
                    "valueCodeableConcept": {
                        "coding": [
                            {
                                "system": "https://www.netzwerk-universitaetsmedizin.de/fhir/CodeSystem/sofa-score",
                                "code": "ns4",
                                "display": "Nervous system SOFA score 4"
                            }
                        ],
                        "text": "Glasgow Coma Scale (GCS) < 6"
                    }
                },
                {
                    "code": {
                        "coding": [
                            {
                                "system": "https://www.netzwerk-universitaetsmedizin.de/fhir/CodeSystem/sofa-score",
                                "code": "cvs",
                                "display": "Cardiovascular system"
                            }
                        ],
                        "text": "SOFA Cardiovascular system scoring category"
                    },
                    "valueCodeableConcept": {
                        "coding": [
                            {
                                "system": "https://www.netzwerk-universitaetsmedizin.de/fhir/CodeSystem/sofa-score",
                                "code": "cvs1",
                                "display": "Cardiovascular system SOFA score 1"
                            }
                        ],
                        "text": "Mean arterial pressure (MAP) < 70 mmHg"
                    }
                },
                {
                    "code": {
                        "coding": [
                            {
                                "system": "https://www.netzwerk-universitaetsmedizin.de/fhir/CodeSystem/sofa-score",
                                "code": "liv",
                                "display": "Liver"
                            }
                        ],
                        "text": "SOFA Liver scoring category"
                    },
                    "valueCodeableConcept": {
                        "coding": [
                            {
                                "system": "https://www.netzwerk-universitaetsmedizin.de/fhir/CodeSystem/sofa-score",
                                "code": "liv1",
                                "display": "Liver SOFA score 1"
                            }
                        ],
                        "text": "Bilirubin (mg/dl) [umol/L] 1.2-1.9 [20-32]"
                    }
                },
                {
                    "code": {
                        "coding": [
                            {
                                "system": "https://www.netzwerk-universitaetsmedizin.de/fhir/CodeSystem/sofa-score",
                                "code": "coa",
                                "display": "Coagulation"
                            }
                        ],
                        "text": "SOFA Coagulation scoring category"
                    },
                    "valueCodeableConcept": {
                        "coding": [
                            {
                                "system": "https://www.netzwerk-universitaetsmedizin.de/fhir/CodeSystem/sofa-score",
                                "code": "coa2",
                                "display": "Coagulation SOFA score 2"
                            }
                        ],
                        "text": "Platelets×10^3/ul < 100"
                    }
                },
                {
                    "code": {
                        "coding": [
                            {
                                "system": "https://www.netzwerk-universitaetsmedizin.de/fhir/CodeSystem/sofa-score",
                                "code": "kid",
                                "display": "Kidneys"
                            }
                        ],
                        "text": "SOFA Kidneys scoring category"
                    },
                    "valueCodeableConcept": {
                        "coding": [
                            {
                                "system": "https://www.netzwerk-universitaetsmedizin.de/fhir/CodeSystem/sofa-score",
                                "code": "kid4",
                                "display": "Kidneys SOFA score 4"
                            }
                        ],
                        "text": "Creatinine (mg/dl) [umol/L] (or urine output) > 5.0 [> 440] (or < 200 ml/d)"
                    }
                }
            ]
        },
        "headers": {
            "Accept": "application/json",
            "Content-Type": "application/json",
            "User-Agent": "RESTinstance/1.0.0",
            "Prefer": "return=representation",
            "Authorization": "Basic bXl1c2VyOm15UGFzc3dvcmQ0MzI="
        },
        "proxies": {},
        "timeout": [
            null,
            null
        ],
        "cert": null,
        "sslVerify": false,
        "allowRedirects": true,
        "timestamp": {
            "utc": "2021-04-14T12:33:55.399282+00:00",
            "local": "2021-04-14T12:33:55.399282+00:00"
        }
    },
    "response": {
        "seconds": 0.161918,
        "status": 500,
        "body": {
            "resourceType": "OperationOutcome",
            "issue": [
                {
                    "severity": "error",
                    "code": "processing",
                    "diagnostics": "Unexpected server error"
                }
            ]
        },
        "headers": {
            "Vary": "Origin, Access-Control-Request-Method, Access-Control-Request-Headers",
            "X-Powered-By": "HAPI FHIR 5.2.0 REST Server (FHIR Server; FHIR 4.0.1/R4)",
            "X-Request-ID": "lIhXzZ78BHseuAjN",
            "Content-Type": "application/fhir+json;charset=UTF-8",
            "Transfer-Encoding": "chunked",
            "Date": "Wed, 14 Apr 2021 12:33:55 GMT",
            "Connection": "close"
        }
    }
}
```

## Actual Result

500 - Unexpected server error

```
fhir-bridge_1  | ca.uhn.fhir.rest.server.exceptions.InternalErrorException: Unexpected server error
fhir-bridge_1  |        at org.openehealth.ipf.platform.camel.ihe.fhir.core.FhirConsumer.runRoute(FhirConsumer.java:203) ~[ipf-platform-camel-ihe-fhir-core-4.0.0.jar:na]
fhir-bridge_1  |        at org.openehealth.ipf.platform.camel.ihe.fhir.core.FhirConsumer.handleInRoute(FhirConsumer.java:165) ~[ipf-platform-camel-ihe-fhir-core-4.0.0.jar:na]
fhir-bridge_1  |        at org.openehealth.ipf.platform.camel.ihe.fhir.core.FhirConsumer.handleAction(FhirConsumer.java:137) ~[ipf-platform-camel-ihe-fhir-core-4.0.0.jar:na]
fhir-bridge_1  |        at org.openehealth.ipf.commons.ihe.fhir.AbstractPlainProvider.requestAction(AbstractPlainProvider.java:170) ~[ipf-commons-ihe-fhir-core-4.0.0.jar:na]
fhir-bridge_1  |        at org.ehrbase.fhirbridge.fhir.observation.CreateObservationProvider.createObservation(CreateObservationProvider.java:40) ~[classes/:na]
fhir-bridge_1  |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
fhir-bridge_1  |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
fhir-bridge_1  |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
fhir-bridge_1  |        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
fhir-bridge_1  |        at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:245) ~[hapi-fhir-server-5.2.0.jar:na]
fhir-bridge_1  |        at ca.uhn.fhir.rest.server.method.BaseOutcomeReturningMethodBinding.invokeServer(BaseOutcomeReturningMethodBinding.java:154) ~[hapi-fhir-server-5.2.0.jar:na]
fhir-bridge_1  |        at ca.uhn.fhir.rest.server.method.CreateMethodBinding.invokeServer(CreateMethodBinding.java:41) ~[hapi-fhir-server-5.2.0.jar:na]
fhir-bridge_1  |        at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1052) ~[hapi-fhir-server-5.2.0.jar:na]
fhir-bridge_1  |        at ca.uhn.fhir.rest.server.RestfulServer.doPost(RestfulServer.java:377) ~[hapi-fhir-server-5.2.0.jar:na]
fhir-bridge_1  |        at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1749) ~[hapi-fhir-server-5.2.0.jar:na]
fhir-bridge_1  |        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar:4.0.1]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[spring-web-5.3.2.jar:5.3.2]
fhir-bridge_1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.2.jar:5.3.2]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.2.jar:5.3.2]
fhir-bridge_1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.2.jar:5.3.2]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.2.jar:5.3.2]
fhir-bridge_1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.2.jar:5.3.2]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) ~[spring-boot-actuator-2.4.1.jar:2.4.1]
fhir-bridge_1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.2.jar:5.3.2]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.2.jar:5.3.2]
fhir-bridge_1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.2.jar:5.3.2]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
fhir-bridge_1  |        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
fhir-bridge_1  |        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
fhir-bridge_1  | Caused by: org.hl7.fhir.exceptions.FHIRException: Type mismatch: the type DateTimeType was expected, but org.hl7.fhir.r4.model.InstantType was encountered
fhir-bridge_1  |        at org.hl7.fhir.r4.model.Observation.getEffectiveDateTimeType(Observation.java:2024) ~[org.hl7.fhir.r4-5.2.0.jar:na]
fhir-bridge_1  |        at org.ehrbase.fhirbridge.ehr.converter.generic.TimeConverter.convertObservationTime(TimeConverter.java:34) ~[classes/:na]
fhir-bridge_1  |        at org.ehrbase.fhirbridge.ehr.converter.generic.ObservationToObservationConverter.invokeOriginValue(ObservationToObservationConverter.java:39) ~[classes/:na]
fhir-bridge_1  |        at org.ehrbase.fhirbridge.ehr.converter.generic.ObservationToObservationConverter.invokeTimeValues(ObservationToObservationConverter.java:21) ~[classes/:na]
fhir-bridge_1  |        at org.ehrbase.fhirbridge.ehr.converter.generic.ObservationToObservationConverter.convert(ObservationToObservationConverter.java:16) ~[classes/:na]
fhir-bridge_1  |        at org.ehrbase.fhirbridge.ehr.converter.specific.sofascore.SofaScoreCompositionConverter.convertInternal(SofaScoreCompositionConverter.java:15) ~[classes/:na]
fhir-bridge_1  |        at org.ehrbase.fhirbridge.ehr.converter.specific.sofascore.SofaScoreCompositionConverter.convertInternal(SofaScoreCompositionConverter.java:8) ~[classes/:na]
fhir-bridge_1  |        at org.ehrbase.fhirbridge.ehr.converter.generic.CompositionConverter.convert(CompositionConverter.java:36) ~[classes/:na]
fhir-bridge_1  |        at org.ehrbase.fhirbridge.ehr.converter.generic.ObservationToCompositionConverter.convert(ObservationToCompositionConverter.java:19) ~[classes/:na]
fhir-bridge_1  |        at org.ehrbase.fhirbridge.ehr.converter.generic.ObservationToCompositionConverter.convert(ObservationToCompositionConverter.java:15) ~[classes/:na]
fhir-bridge_1  |        at org.ehrbase.fhirbridge.ehr.converter.ConversionService.convert(ConversionService.java:41) ~[classes/:na]
fhir-bridge_1  |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
fhir-bridge_1  |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
fhir-bridge_1  |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
fhir-bridge_1  |        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
fhir-bridge_1  |        at org.apache.camel.support.ObjectHelper.invokeMethodSafe(ObjectHelper.java:372) ~[camel-support-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:489) ~[camel-bean-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:311) ~[camel-bean-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:281) ~[camel-bean-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.component.bean.AbstractBeanProcessor.process(AbstractBeanProcessor.java:145) ~[camel-bean-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:68) ~[camel-bean-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.component.bean.BeanProducer.process(BeanProducer.java:41) ~[camel-bean-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:169) ~[camel-core-processor-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:714) ~[camel-core-processor-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:623) ~[camel-core-processor-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:148) ~[camel-base-engine-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:60) ~[camel-base-engine-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.processor.Pipeline.process(Pipeline.java:147) ~[camel-core-processor-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:312) ~[camel-base-engine-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83) ~[camel-base-engine-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41) ~[camel-support-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.openehealth.ipf.platform.camel.ihe.fhir.core.intercept.consumer.ConsumerAuditInterceptor.process(ConsumerAuditInterceptor.java:60) ~[ipf-platform-camel-ihe-fhir-core-4.0.0.jar:na]
fhir-bridge_1  |        at org.openehealth.ipf.platform.camel.ihe.fhir.core.FhirConsumer.runRoute(FhirConsumer.java:192) ~[ipf-platform-camel-ihe-fhir-core-4.0.0.jar:na]
fhir-bridge_1  |        ... 56 common frames omitted
```

## Expected Result

200/204

**Comment by SevKohler** [comment]
fixed in #316
