### ISSUE TITLE
Test fails with error "Start time is not defined in Procedure"

### ISSUE THREAD

**Issue by wlad** [ehrbase/fhir-bridge#301]
## Test Case/s To Reproduce Issue With Robot

```
# path to test case
tests/robot/OBSERVATION/01_create.robot
TC: 005 Create Generic Therapy - Dialysis with not performed "performedPeriod"
```

```
# robot command to execute related test case(s) in your terminal/console

robot -i 301 -d results -L TRACE robot

```

## Steps To Reproduce Manually

```json
{
    "request": {
        "method": "POST",
        "url": "http://localhost:8888/fhir-bridge/fhir/Procedure",
        "scheme": "http",
        "netloc": "localhost:8888",
        "path": "/fhir-bridge/fhir/Procedure",
        "query": {},
        "body": {
            "meta": {
                "profile": [
                    "https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/dialysis"
                ]
            },
            "category": {
                "coding": [
                    {
                        "code": "277132007",
                        "display": "Therapeutic procedure (procedure)",
                        "system": "http://snomed.info/sct"
                    }
                ]
            },
            "code": {
                "coding": [
                    {
                        "code": "108241001",
                        "display": "Dialysis procedure (procedure)",
                        "system": "http://snomed.info/sct"
                    }
                ]
            },
            "performedPeriod": {
                "extension": [
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
                        "valueCode": "not-performed"
                    }
                ]
            },
            "status": "not-done",
            "subject": {
                "identifier": {
                    "system": "urn:ietf:rfc:4122",
                    "value": "5b76a708-8ff3-448a-bba7-b9bb2461e2b7"
                }
            },
            "resourceType": "Procedure"
        },
        "headers": {
            "Accept": "application/json",
            "Content-Type": "application/json",
            "User-Agent": "RESTinstance/1.0.2",
            "Prefer": "return=representation",
            "Authorization": "Basic bXl1c2VyOm15UGFzc3dvcmQ0MzI="
        },
        "proxies": {},
        "timeout": [
            null,
            null
        ],
        "cert": null,
        "sslVerify": false,
        "allowRedirects": true,
        "timestamp": {
            "utc": "2021-04-14T19:09:05.834000+00:00",
            "local": "2021-04-14T21:09:05.834000+02:00"
        }
    },
    "response": {
        "seconds": 0.261206,
        "status": 422,
        "body": {
            "resourceType": "OperationOutcome",
            "issue": [
                {
                    "severity": "error",
                    "code": "processing",
                    "diagnostics": "Start time is not defined in Procedure"
                }
            ]
        },
        "headers": {
            "Vary": "Origin, Access-Control-Request-Method, Access-Control-Request-Headers",
            "X-Powered-By": "HAPI FHIR 5.2.0 REST Server (FHIR Server; FHIR 4.0.1/R4)",
            "X-Request-ID": "37urbQ2I39Z8LzzU",
            "Content-Type": "application/fhir+json;charset=UTF-8",
            "Transfer-Encoding": "chunked",
            "Date": "Wed, 14 Apr 2021 19:09:05 GMT",
            "Keep-Alive": "timeout=60",
            "Connection": "keep-alive"
        }
    }
}
```

## Actual Result

422

```
fhir-bridge_1  | ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: Start time is not defined in Procedure
fhir-bridge_1  |        at org.ehrbase.fhirbridge.camel.processor.DefaultExceptionHandler.handleConversionException(DefaultExceptionHandler.java:37) ~[classes/:na]
fhir-bridge_1  |        at org.ehrbase.fhirbridge.camel.processor.DefaultExceptionHandler.process(DefaultExceptionHandler.java:27) ~[classes/:na]
fhir-bridge_1  |        at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:66) ~[camel-support-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:312) ~[camel-base-engine-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.processor.FatalFallbackErrorHandler.process(FatalFallbackErrorHandler.java:83) ~[camel-core-processor-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.deliverToFailureProcessor(RedeliveryErrorHandler.java:1080) ~[camel-core-processor-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:656) ~[camel-core-processor-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:623) ~[camel-core-processor-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:148) ~[camel-base-engine-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:60) ~[camel-base-engine-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.processor.Pipeline.process(Pipeline.java:147) ~[camel-core-processor-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:312) ~[camel-base-engine-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83) ~[camel-base-engine-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41) ~[camel-support-3.7.0.jar:3.7.0]
fhir-bridge_1  |        at org.openehealth.ipf.platform.camel.ihe.fhir.core.intercept.consumer.ConsumerAuditInterceptor.process(ConsumerAuditInterceptor.java:60) ~[ipf-platform-camel-ihe-fhir-core-4.0.0.jar:na]
fhir-bridge_1  |        at org.openehealth.ipf.platform.camel.ihe.fhir.core.FhirConsumer.runRoute(FhirConsumer.java:192) ~[ipf-platform-camel-ihe-fhir-core-4.0.0.jar:na]
fhir-bridge_1  |        at org.openehealth.ipf.platform.camel.ihe.fhir.core.FhirConsumer.handleInRoute(FhirConsumer.java:165) ~[ipf-platform-camel-ihe-fhir-core-4.0.0.jar:na]
fhir-bridge_1  |        at org.openehealth.ipf.platform.camel.ihe.fhir.core.FhirConsumer.handleAction(FhirConsumer.java:137) ~[ipf-platform-camel-ihe-fhir-core-4.0.0.jar:na]
fhir-bridge_1  |        at org.openehealth.ipf.commons.ihe.fhir.AbstractPlainProvider.requestAction(AbstractPlainProvider.java:170) ~[ipf-commons-ihe-fhir-core-4.0.0.jar:na]
fhir-bridge_1  |        at org.ehrbase.fhirbridge.fhir.procedure.CreateProcedureProvider.createProcedure(CreateProcedureProvider.java:41) ~[classes/:na]
fhir-bridge_1  |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
fhir-bridge_1  |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
fhir-bridge_1  |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
fhir-bridge_1  |        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
fhir-bridge_1  |        at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:245) ~[hapi-fhir-server-5.2.0.jar:na]
fhir-bridge_1  |        at ca.uhn.fhir.rest.server.method.BaseOutcomeReturningMethodBinding.invokeServer(BaseOutcomeReturningMethodBinding.java:154) ~[hapi-fhir-server-5.2.0.jar:na]
fhir-bridge_1  |        at ca.uhn.fhir.rest.server.method.CreateMethodBinding.invokeServer(CreateMethodBinding.java:41) ~[hapi-fhir-server-5.2.0.jar:na]
fhir-bridge_1  |        at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1052) ~[hapi-fhir-server-5.2.0.jar:na]
fhir-bridge_1  |        at ca.uhn.fhir.rest.server.RestfulServer.doPost(RestfulServer.java:377) ~[hapi-fhir-server-5.2.0.jar:na]
fhir-bridge_1  |        at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1749) ~[hapi-fhir-server-5.2.0.jar:na]
fhir-bridge_1  |        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar:4.0.1]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[spring-web-5.3.2.jar:5.3.2]
fhir-bridge_1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.2.jar:5.3.2]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.2.jar:5.3.2]
fhir-bridge_1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.2.jar:5.3.2]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.2.jar:5.3.2]
fhir-bridge_1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.2.jar:5.3.2]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) ~[spring-boot-actuator-2.4.1.jar:2.4.1]
fhir-bridge_1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.2.jar:5.3.2]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.2.jar:5.3.2]
fhir-bridge_1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.2.jar:5.3.2]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
fhir-bridge_1  |        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
fhir-bridge_1  |        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
fhir-bridge_1  |        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
fhir-bridge_1  | 
fhir-bridge_1  | Hibernate: 
fhir-bridge_1  |     select
fhir-bridge_1  |         resourceta0_.RES_TYPE as col_0_0_,
fhir-bridge_1  |         resourceta0_.RES_ID as col_1_0_,
fhir-bridge_1  |         resourceta0_.RES_DELETED_AT as col_2_0_ 
fhir-bridge_1  |     from
fhir-bridge_1  |         HFJ_RESOURCE resourceta0_ 
fhir-bridge_1  |     where
fhir-bridge_1  |         resourceta0_.RES_ID in (
fhir-bridge_1  |             ?
fhir-bridge_1  |         )
fhir-bridge_1  | Hibernate: 
fhir-bridge_1  |     insert 
fhir-bridge_1  |     into
fhir-bridge_1  |         HFJ_RESOURCE
fhir-bridge_1  |         (PARTITION_DATE, PARTITION_ID, RES_DELETED_AT, RES_VERSION, HAS_TAGS, RES_PUBLISHED, RES_UPDATED, SP_HAS_LINKS, HASH_SHA256, SP_INDEX_STATUS, RES_LANGUAGE, SP_CMPSTR_UNIQ_PRESENT, SP_COORDS_PRESENT, SP_DATE_PRESENT, SP_NUMBER_PRESENT, SP_QUANTITY_PRESENT, SP_STRING_PRESENT, SP_TOKEN_PRESENT, SP_URI_PRESENT, RES_TYPE, RES_VER, RES_ID) 
fhir-bridge_1  |     values
fhir-bridge_1  |         (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
fhir-bridge_1  | Hibernate: 
fhir-bridge_1  |     insert 
fhir-bridge_1  |     into
fhir-bridge_1  |         HFJ_RES_VER
fhir-bridge_1  |         (PARTITION_DATE, PARTITION_ID, RES_DELETED_AT, RES_VERSION, HAS_TAGS, RES_PUBLISHED, RES_UPDATED, RES_ENCODING, RES_TEXT, RES_ID, RES_TYPE, RES_VER, PID) 
fhir-bridge_1  |     values
fhir-bridge_1  |         (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
fhir-bridge_1  | Hibernate: 
fhir-bridge_1  |     insert 
fhir-bridge_1  |     into
fhir-bridge_1  |         HFJ_SPIDX_STRING
fhir-bridge_1  |         (PARTITION_DATE, PARTITION_ID, SP_MISSING, SP_NAME, RES_ID, RES_TYPE, SP_UPDATED, HASH_EXACT, HASH_IDENTITY, HASH_NORM_PREFIX, SP_VALUE_EXACT, SP_VALUE_NORMALIZED, SP_ID) 
fhir-bridge_1  |     values
fhir-bridge_1  |         (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
fhir-bridge_1  | Hibernate: 
fhir-bridge_1  |     insert 
fhir-bridge_1  |     into
fhir-bridge_1  |         HFJ_SPIDX_STRING
fhir-bridge_1  |         (PARTITION_DATE, PARTITION_ID, SP_MISSING, SP_NAME, RES_ID, RES_TYPE, SP_UPDATED, HASH_EXACT, HASH_IDENTITY, HASH_NORM_PREFIX, SP_VALUE_EXACT, SP_VALUE_NORMALIZED, SP_ID) 
fhir-bridge_1  |     values
fhir-bridge_1  |         (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
fhir-bridge_1  | Hibernate: 
fhir-bridge_1  |     insert 
fhir-bridge_1  |     into
fhir-bridge_1  |         HFJ_SPIDX_STRING
fhir-bridge_1  |         (PARTITION_DATE, PARTITION_ID, SP_MISSING, SP_NAME, RES_ID, RES_TYPE, SP_UPDATED, HASH_EXACT, HASH_IDENTITY, HASH_NORM_PREFIX, SP_VALUE_EXACT, SP_VALUE_NORMALIZED, SP_ID) 
fhir-bridge_1  |     values
fhir-bridge_1  |         (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
fhir-bridge_1  | Hibernate: 
fhir-bridge_1  |     insert 
fhir-bridge_1  |     into
fhir-bridge_1  |         HFJ_SPIDX_TOKEN
fhir-bridge_1  |         (PARTITION_DATE, PARTITION_ID, SP_MISSING, SP_NAME, RES_ID, RES_TYPE, SP_UPDATED, HASH_IDENTITY, HASH_SYS, HASH_SYS_AND_VALUE, HASH_VALUE, SP_SYSTEM, SP_VALUE, SP_ID) 
fhir-bridge_1  |     values
fhir-bridge_1  |         (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
fhir-bridge_1  | Hibernate: 
fhir-bridge_1  |     insert 
fhir-bridge_1  |     into
fhir-bridge_1  |         HFJ_SPIDX_TOKEN
fhir-bridge_1  |         (PARTITION_DATE, PARTITION_ID, SP_MISSING, SP_NAME, RES_ID, RES_TYPE, SP_UPDATED, HASH_IDENTITY, HASH_SYS, HASH_SYS_AND_VALUE, HASH_VALUE, SP_SYSTEM, SP_VALUE, SP_ID) 
fhir-bridge_1  |     values
fhir-bridge_1  |         (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
fhir-bridge_1  | Hibernate: 
fhir-bridge_1  |     insert 
fhir-bridge_1  |     into
fhir-bridge_1  |         HFJ_SPIDX_TOKEN
fhir-bridge_1  |         (PARTITION_DATE, PARTITION_ID, SP_MISSING, SP_NAME, RES_ID, RES_TYPE, SP_UPDATED, HASH_IDENTITY, HASH_SYS, HASH_SYS_AND_VALUE, HASH_VALUE, SP_SYSTEM, SP_VALUE, SP_ID) 
fhir-bridge_1  |     values
fhir-bridge_1  |         (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
fhir-bridge_1  | Hibernate: 
fhir-bridge_1  |     insert 
fhir-bridge_1  |     into
fhir-bridge_1  |         HFJ_SPIDX_TOKEN
fhir-bridge_1  |         (PARTITION_DATE, PARTITION_ID, SP_MISSING, SP_NAME, RES_ID, RES_TYPE, SP_UPDATED, HASH_IDENTITY, HASH_SYS, HASH_SYS_AND_VALUE, HASH_VALUE, SP_SYSTEM, SP_VALUE, SP_ID) 
fhir-bridge_1  |     values
fhir-bridge_1  |         (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
fhir-bridge_1  | Hibernate: 
fhir-bridge_1  |     insert 
fhir-bridge_1  |     into
fhir-bridge_1  |         HFJ_SPIDX_TOKEN
fhir-bridge_1  |         (PARTITION_DATE, PARTITION_ID, SP_MISSING, SP_NAME, RES_ID, RES_TYPE, SP_UPDATED, HASH_IDENTITY, HASH_SYS, HASH_SYS_AND_VALUE, HASH_VALUE, SP_SYSTEM, SP_VALUE, SP_ID) 
fhir-bridge_1  |     values
fhir-bridge_1  |         (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
fhir-bridge_1  | Hibernate: 
fhir-bridge_1  |     insert 
fhir-bridge_1  |     into
fhir-bridge_1  |         HFJ_SPIDX_DATE
fhir-bridge_1  |         (PARTITION_DATE, PARTITION_ID, SP_MISSING, SP_NAME, RES_ID, RES_TYPE, SP_UPDATED, HASH_IDENTITY, SP_VALUE_HIGH, SP_VALUE_HIGH_DATE_ORDINAL, SP_VALUE_LOW, SP_VALUE_LOW_DATE_ORDINAL, SP_ID) 
fhir-bridge_1  |     values
fhir-bridge_1  |         (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
fhir-bridge_1  | Hibernate: 
fhir-bridge_1  |     insert 
fhir-bridge_1  |     into
fhir-bridge_1  |         HFJ_RES_LINK
fhir-bridge_1  |         (PARTITION_DATE, PARTITION_ID, SRC_PATH, SRC_RESOURCE_ID, SOURCE_RESOURCE_TYPE, TARGET_RESOURCE_ID, TARGET_RESOURCE_TYPE, TARGET_RESOURCE_URL, SP_UPDATED, PID) 
fhir-bridge_1  |     values
fhir-bridge_1  |         (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
fhir-bridge_1  | 2021-04-14 18:54:14.928  WARN 1 --- [nio-8888-exec-2] c.u.f.r.s.i.ExceptionHandlingInterceptor : Failure during REST processing: ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: Start time is not defined in Procedure
```

## Expected Result

200/204

**Comment by SevKohler** [comment]
fixed in #313  
@wlad can you check
