### ISSUE TITLE
Fehlermeldung bei Mapping von Encounter -> Patienten Aufenthalt

### ISSUE THREAD

**Issue by ZhuYufei990** [ehrbase/fhir-bridge#332]
## Steps to reproduce ## 

checkout feature/NUM_119_Stat_Versorgunsfall+Patientenaufenthalt, import the Postman Collection in ./config/postman/fhir-bridge.postman_collection.json , try the request FHIR->Encounter->Create Patienten Aufenthalt

## Actual result ##

c.u.f.r.s.i.ExceptionHandlingInterceptor : Failure during REST processing
 
ca.uhn.fhir.rest.server.exceptions.InternalErrorException: Method createEncounter in type org.ehrbase.fhirbridge.fhir.encounter.CreateEncounterProvider returned null
        at ca.uhn.fhir.rest.server.method.BaseOutcomeReturningMethodBinding.validateResponseNotNullIfItShouldntBe(BaseOutcomeReturningMethodBinding.java:109) ~[hapi-fhir-server-5.3.0.jar!/:na]
        at ca.uhn.fhir.rest.server.method.BaseOutcomeReturningMethodBinding.getOperationStatus(BaseOutcomeReturningMethodBinding.java:81) ~[hapi-fhir-server-5.3.0.jar!/:na]
        at ca.uhn.fhir.rest.server.method.BaseOutcomeReturningMethodBinding.returnResponse(BaseOutcomeReturningMethodBinding.java:181) ~[hapi-fhir-server-5.3.0.jar!/:na]
        at ca.uhn.fhir.rest.server.method.BaseOutcomeReturningMethodBinding.invokeServer(BaseOutcomeReturningMethodBinding.java:171) ~[hapi-fhir-server-5.3.0.jar!/:na]
        at ca.uhn.fhir.rest.server.method.CreateMethodBinding.invokeServer(CreateMethodBinding.java:41) ~[hapi-fhir-server-5.3.0.jar!/:na]
        at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1084) ~[hapi-fhir-server-5.3.0.jar!/:na]
        at ca.uhn.fhir.rest.server.RestfulServer.doPost(RestfulServer.java:390) ~[hapi-fhir-server-5.3.0.jar!/:na]
        at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1800) ~[hapi-fhir-server-5.3.0.jar!/:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.41.jar!/:4.0.FR]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]

## Expected result ##
Describe the expected output / behaviour.

201 created
## Success criteria ##

- [ ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by SevKohler** [comment]
```Java
    .when(header(FhirBridgeConstants.PROFILE).isEqualTo(Profile.PATIENTEN_AUFENTHALT))
                        .to("bean:fhirResourceConversionService?method=convert(${headers.FhirBridgeProfile}, ${body})")
                        .to("ehr-composition:compositionEndpoint?operation=mergeCompositionEntity")
                .otherwise()
                        .to("bean:fhirResourceConversionService?method=convertDefaultEncounter(${body})")
                        .to("ehr-composition:compositionEndpoint?operation=mergeCompositionEntity")
               .process("resourceResponseProcessor");
         
```
Should do the trick

**Comment by SevKohler** [comment]
I pushed it, you just need to pull !
