### ISSUE TITLE
FHIR-Bridge version 1.2.0 fails to authenticate with EHRBase using basic auth

### ISSUE THREAD

**Issue by StefanWinterfeldtVitasystems** [ehrbase/fhir-bridge#366]
## Steps to reproduce ## 

I have a Kubernetes namespace with an instance of EHRBase (0.16.5) and FHIR-Bridge (1.1.1). FHIR-Bridge is configured to authenticate with EHRBase using basic auth, it works as expected.
When I upgrade the version of FHIR-Bridge to 1.2.0 (changing nothing else), FHIR-Bridge fails to start.
Rolling back the version of FHIR-Bridge to 1.1.1 makes everything work again.

## Actual result ##

FHIR-Bridge fails to start with this error:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'templateInitializer' defined in class path resource [org/ehrbase/fhirbridge/config/ehrbase/EhrbaseConfiguration.class]: Invocation of init method failed; nested exception is org.ehrbase.client.exception.WrongStatusCodeException: Wrong Status code. Expected: [200, 404]. Got: 401. Error message:
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438) ~[spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:337) ~[spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1336) ~[spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1325) ~[spring-boot-2.5.0.jar:2.5.0]
	at org.ehrbase.fhirbridge.FhirBridgeApplication.main(FhirBridgeApplication.java:10) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[workspace/:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[workspace/:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[workspace/:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[workspace/:na]
Caused by: org.ehrbase.client.exception.WrongStatusCodeException: Wrong Status code. Expected: [200, 404]. Got: 401. Error message:
	at org.ehrbase.client.openehrclient.defaultrestclient.DefaultRestClient.checkStatus(DefaultRestClient.java:265) ~[client-develop-v0.3.7-gf76a4ec-508.jar:na]
	at org.ehrbase.client.openehrclient.defaultrestclient.DefaultRestClient.internalGet(DefaultRestClient.java:212) ~[client-develop-v0.3.7-gf76a4ec-508.jar:na]
	at org.ehrbase.client.openehrclient.defaultrestclient.DefaultRestTemplateEndpoint.findTemplate(DefaultRestTemplateEndpoint.java:72) ~[client-develop-v0.3.7-gf76a4ec-508.jar:na]
	at org.ehrbase.fhirbridge.config.ehrbase.EhrbaseTemplateInitializer.afterPropertiesSet(EhrbaseTemplateInitializer.java:71) ~[classes/:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[spring-beans-5.3.7.jar:5.3.7]
	... 24 common frames omitted
```

## Expected result ##

FHIR-Bridge initializes correctly.

## Success criteria ##

- [ ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by subigre** [comment]
Hi @StefanWinterfeldtVitasystems 
I apologize because I did some changes in the configuration file when I have added support for OAuth2 (https://github.com/ehrbase/fhir-bridge/issues/349) but I forgot to inform you 😢 

The following environment variables:
```properties
FHIR_BRIDGE_EHRBASE_SECURITY_USER=<user>
FHIR_BRIDGE_EHRBASE_SECURITY_PASSWORD=<password>
FHIR_BRIDGE_EHRBASE_SECURITY_ADMIN_USER=<admin_user>
FHIR_BRIDGE_EHRBASE_SECURITY_ADMIN_PASSWORD=<admin_password>
```
must be updated to:
```properties
FHIR_BRIDGE_EHRBASE_SECURITY_USER_NAME=<user>
FHIR_BRIDGE_EHRBASE_SECURITY_USER_PASSWORD=<password>
FHIR_BRIDGE_EHRBASE_SECURITY_USER_ADMIN_NAME=<admin_user>
FHIR_BRIDGE_EHRBASE_SECURITY_USER_ADMIN_PASSWORD=<admin_password>
```

**Comment by StefanWinterfeldtVitasystems** [comment]
Hi @subigre,
that works for me, FHIR-Bridge is able to authenticate again, thanks!
