### ISSUE TITLE
Fhir Bridge crashes on startup: "Error creating bean with name 'deleteObjectProcessor' defined in URL"

### ISSUE THREAD

**Issue by NormanWeinert** [ehrbase/fhir-bridge#463]
I installed fhir-bridge via "mvn clean install" after cloning the repository.

Starting fhir-bridge with "java -jar target/fhir-bridge-1.3.0-SNAPSHOT.jar" results in the following error:

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'deleteObjectProcessor' defined in URL [jar:file:/C:/Projects/fhir/fhir-bridge-clone/fhir-bridge/target/fhir-bridge-1.3.0-SNAPSHOT.jar!/BOOT-INF/classes!/org/ehrbase/fhirbridge/camel/processor/DeleteObjectProcessor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'minioService' defined in class path resource [org/ehrbase/fhirbridge/config/minio/MinioConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ehrbase.fhirbridge.minio.MinioService]: Factory method 'minioService' threw exception; nested exception is org.ehrbase.fhirbridge.minio.MinioException: Error occurred while checking if the specified bucket exists
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.9.jar!/:5.3.9]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.9.jar!/:5.3.9]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.4.jar!/:2.5.4]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-2.5.4.jar!/:2.5.4]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-2.5.4.jar!/:2.5.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.4.jar!/:2.5.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.4.jar!/:2.5.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.4.jar!/:2.5.4]
        at org.ehrbase.fhirbridge.FhirBridgeApplication.main(FhirBridgeApplication.java:10) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[fhir-bridge-1.3.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[fhir-bridge-1.3.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[fhir-bridge-1.3.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[fhir-bridge-1.3.0-SNAPSHOT.jar:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'minioService' defined in class path resource [org/ehrbase/fhirbridge/config/minio/MinioConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ehrbase.fhirbridge.minio.MinioService]: Factory method 'minioService' threw exception; nested exception is org.ehrbase.fhirbridge.minio.MinioException: Error occurred while checking if the specified bucket exists
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.9.jar!/:5.3.9]
        ... 27 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ehrbase.fhirbridge.minio.MinioService]: Factory method 'minioService' threw exception; nested exception is org.ehrbase.fhirbridge.minio.MinioException: Error occurred while checking if the specified bucket exists
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.9.jar!/:5.3.9]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.9.jar!/:5.3.9]
        ... 41 common frames omitted
Caused by: org.ehrbase.fhirbridge.minio.MinioException: Error occurred while checking if the specified bucket exists
        at org.ehrbase.fhirbridge.config.minio.MinioConfiguration.minioService(MinioConfiguration.java:59) ~[classes!/:na]
        at org.ehrbase.fhirbridge.config.minio.MinioConfiguration$$EnhancerBySpringCGLIB$$866d19e.CGLIB$minioService$0(<generated>) ~[classes!/:na]
        at org.ehrbase.fhirbridge.config.minio.MinioConfiguration$$EnhancerBySpringCGLIB$$866d19e$$FastClassBySpringCGLIB$$bf5b2416.invoke(<generated>) ~[classes!/:na]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.9.jar!/:5.3.9]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.9.jar!/:5.3.9]
        at org.ehrbase.fhirbridge.config.minio.MinioConfiguration$$EnhancerBySpringCGLIB$$866d19e.minioService(<generated>) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.9.jar!/:5.3.9]
        ... 42 common frames omitted
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:9000
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297) ~[okhttp-4.8.1.jar!/:na]
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207) ~[okhttp-4.8.1.jar!/:na]
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226) ~[okhttp-4.8.1.jar!/:na]
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) ~[okhttp-4.8.1.jar!/:na]
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) ~[okhttp-4.8.1.jar!/:na]
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) ~[okhttp-4.8.1.jar!/:na]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.8.1.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.8.1.jar!/:na]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.8.1.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.8.1.jar!/:na]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.8.1.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.8.1.jar!/:na]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.8.1.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.8.1.jar!/:na]
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.8.1.jar!/:na]
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[okhttp-4.8.1.jar!/:na]
        at io.minio.S3Base.execute(S3Base.java:532) ~[minio-8.3.0.jar!/:8.3.0]
        at io.minio.S3Base.getRegion(S3Base.java:694) ~[minio-8.3.0.jar!/:8.3.0]
        at io.minio.S3Base.execute(S3Base.java:470) ~[minio-8.3.0.jar!/:8.3.0]
        at io.minio.S3Base.executeHead(S3Base.java:728) ~[minio-8.3.0.jar!/:8.3.0]
        at io.minio.MinioClient.bucketExists(MinioClient.java:1135) ~[minio-8.3.0.jar!/:8.3.0]
        at org.ehrbase.fhirbridge.config.minio.MinioConfiguration.minioService(MinioConfiguration.java:48) ~[classes!/:na]
        ... 52 common frames omitted
        Suppressed: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:9000
                ... 74 common frames omitted
        Caused by: java.net.ConnectException: Connection refused: connect
                at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
                at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
                at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
                at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
                at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
                at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
                at java.base/java.net.Socket.connect(Socket.java:609)
                at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
                at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
                ... 73 common frames omitted
Caused by: java.net.ConnectException: Connection refused: connect
        at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method) ~[na:na]
        at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107) ~[na:na]
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:na]
        at java.base/java.net.Socket.connect(Socket.java:609) ~[na:na]
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120) ~[okhttp-4.8.1.jar!/:na]
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295) ~[okhttp-4.8.1.jar!/:na]
        ... 73 common frames omitted
```

It seems like the error results in a class added in the following recent commit: https://github.com/ehrbase/fhir-bridge/commit/d1105eeae73b994b4dfaa44ea59fde3bc35a17d1
The class being "DeleteObjectProcessor.java".

I first suspected something being wrong with my older installation, but even with a freshly cloned one the error still remains. As a result, I suspect a bug.

**Comment by subigre** [comment]
Hi @NormanWeinert, how did you start EHRbase and the database? Did you use the `docker-compose-light.yml` file?

**Comment by birgerhaarbrandt** [comment]
@subigre I tried myself and this might be related to the MinIO. Is it possible to remove the need to connect to MinIO using the config file?

**Comment by NormanWeinert** [comment]
I started EHRbase with "java -jar application/target/application-0.16.5.jar" as usual.

I set up the database back when I started with the fhir-bridge through running "cloud-db-setup.sql" with psql and getting the output:

CREATE DATABASE
GRANT
You are now connected to database "ehrbase" as user "postgres".
CREATE SCHEMA
CREATE SCHEMA
CREATE EXTENSION
CREATE EXTENSION
ALTER DATABASE
GRANT
CREATE FUNCTION

Everything was running before. The only change was that I just pulled the new fhir version today and got the error on start.

**Comment by subigre** [comment]
@birgerhaarbrandt You are right, it is related to MinIO because the FHIR Bridge tries to initialize the MinioClient during startup process.

I haved  updated the Docker Compose files to start MinIO as a container:
```yaml
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123456
    command: server /data --console-address ":9001"
```

**Comment by NormanWeinert** [comment]
Due to the recent commit I am able to install and start FHIR Bridge without problems anymore.
Thanks for addressing this!

**Comment by subigre** [comment]
You're welcome 😃
