### ISSUE TITLE
Maven build fails:  Jitpack  Dependencies not resolving/downloading  whether behind corperate Proxy or not. 

### ISSUE THREAD

**Issue by CzarMich** [ehrbase/fhir-bridge#530]
On trying to Move to infrastructure behind proxy from Local machine, I  am not able to get Jitpack dependencies. 
Any help?

I cannot seem to get past 

"Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.5.5/spring-boot-dependencies-2.5.5.pom".  (on VM behind proxy)

And after installation of fresh VM; with only JDK and Maven,
I get this error:

[ERROR] Failed to execute goal on project fhir-bridge: Could not resolve dependencies for project org.ehrbase.fhirbridge:fhir-bridge:jar:1.5.0-SNAPSHOT: Could not find artifact com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.13.3 in jitpack.io (https://jitpack.io) 

Locally, Eclipse prints the response below.  Any advise. 
thanks

`[ERROR] Failed to execute goal on project fhir-bridge: Could not resolve dependencies for project org.ehrbase.fhirbridge:fhir-bridge:jar:1.5.0-SNAPSHOT: The following artifacts could not be resolved: com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.13.3, com.github.ehrbase:openEHR_SDK:jar:10cce9b: com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.13.3 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of maven.apache.org/maven2 has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project fhir-bridge: Could not resolve dependencies for project org.ehrbase.fhirbridge:fhir-bridge:jar:1.5.0-SNAPSHOT: The following artifacts could not be resolved: com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.13.3, com.github.ehrbase:openEHR_SDK:jar:10cce9b: com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.13.3 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of maven.apache.org/maven2 has elapsed or updates are forced
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:269)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:147)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:248)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:202)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.ehrbase.fhirbridge:fhir-bridge:jar:1.5.0-SNAPSHOT: The following artifacts could not be resolved: com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.13.3, com.github.ehrbase:openEHR_SDK:jar:10cce9b: com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.13.3 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of maven.apache.org/maven2 has elapsed or updates are forced
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:209)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:243)
	... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.13.3, com.github.ehrbase:openEHR_SDK:jar:10cce9b: com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.13.3 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of maven.apache.org/maven2 has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:357)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:202)
	... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.13.3, com.github.ehrbase:openEHR_SDK:jar:10cce9b: com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.13.3 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of maven.apache.org/maven2 has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:424)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:340)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.13.3 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of maven.apache.org/maven2 has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:217)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:189)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:573)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:483)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:401)
	... 27 more
[ERROR] `

**Comment by CzarMich** [comment]
Issue is in the pom.xml file. 
Had to keep activating and deactivate jitpack.io repository  in order to get over certain dependencies. 

`    <repositories>
      <repository>
         <id>jitpack.io</id>
         <url>https://jitpack.io</url>
     </repository>
  </repositories>
`

I changed the SDK version as well after initial run to the value that was in the .m2 repository. 

`        <dependency>
           <groupId>com.github.ehrbase</groupId>
            <artifactId>openEHR_SDK</artifactId>
            <version>10cce9b</version> 
            
`

And then deactivated SDK property after it had been downloaded as it,  was too giving me errors during the build.

`
<properties>
  <ehrbase-sdk.version>10cce9b</ehrbase-sdk.version> 
</properties>

`
Playing around with these 3 sections enable a successful BUILD.

**Comment by geloro94** [comment]
Had the same issue if you landed here this is the solution that worked for me:

delete your m2/repository/com/github/jsonld-java folder.

Remove <repositories> <repository> <id>jitpack.io</id> <url>https://jitpack.io</url> </repository> </repositories> from the pom

Download the dependencies.

Add <repositories> <repository> <id>jitpack.io</id> <url>https://jitpack.io</url> </repository> </repositories> back to your pom
